src/Entity/SimpleCms/Tag.php
<?php

namespace App\Entity\SimpleCms;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SimpleCms\TagRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Tag
{

    use \App\Entity\Traits\CreateUpdateTime;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $server_name;

    /**
     * @ORM\Column(type="integer")
     */
    private $indexNumber;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\App\Article", mappedBy="tags")
     */
    private $articles;

    public function __construct()
    {
        $this->indexNumber = 0;
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): ?self
    {
        $this->name = $name;
        return $this;
    }

    public function getServerName(): ?string
    {
        return $this->server_name;
    }

    public function setServerName(?string $name): ?self
    {
        $this->server_name = $name;
        return $this;
    }

    public function getIndexNumber(): ?int
    {
        return $this->indexNumber;
    }

    public function setIndexNumber(?int $index): ?self
    {
        $this->indexNumber = $index;
        return $this;
    }

    public function getArticles(): ?Collection
    {
        return $this->articles;
    }

}

templates/app/site/general/footer.html.twig
{% import 'app/site/macros/svg.html.twig' as svg %}
{% set page_url = app.request.requestUri %}

<footer class="footer">
    <div class="footer-top">
        <div class="wrapper">
            <div class="footer-top__wrapper">
                <div class="footer-top__col footer-top__col--big">

                    {% if page_url == '/' %}
                        <div class="footer-top__logo is-main">
                            <p class="footer-top__logo-text">Лапа Кота</p>
                            <div class="footer-top__logo-icon">
                                {{ svg.default('cat-paw') }}
                            </div>
                        </div>
                    {% else %}
                        <a class="footer-top__logo" href="/">
                            <span class="footer-top__logo-text">Лапа Кота</span>
                            <span class="footer-top__logo-icon">
                                {{ svg.default('cat-paw') }}
                            </span>
                        </a>
                    {% endif %}

                    <div class="footer-top__pages">

                        {% if navigation.footer_pages %}
                            {% for item in navigation.footer_pages|orderFilter %}

                                {% set page = item.page %}

                                {% if page.published and page.path %}
                                    <a class="footer-top__page" href="{{ path(page.serverName) }}">{{ item.name }}</a>
                                {% endif %}

                            {% endfor %}
                        {% endif %}

                    </div>

                </div>
                <div class="footer-top__col footer-top__col--sections">
                    <div class="footer-top__col-item">
                        <p class="footer-top__col-item-title">Разделы</p>
                        <nav class="footer-top__list">

                            {% if navigation.footer_categories %}
                                {% for item in navigation.footer_categories %}

                                    {% set category = item.category %}

                                    {% if category.published and category.path %}
                                        <div class="footer-top__list-item">
                                            <a class="link" href="{{ path('category', {category_path: category.path}) }}">{{ item.name }}</a>
                                        </div>
                                    {% endif %}

                                {% endfor %}
                            {% endif %}

                        </nav>
                    </div>
                </div>
                <div class="footer-top__col footer-top__col--socials">
                    <div class="footer-top__col-item">
                        <p class="footer-top__col-item-title">Социальные сети</p>
                        <div class="footer-top__socials">

                            {% set socials = global_data.fields.socials %}
                            {% if socials and socials.value %}
                                {% for social in socials.value %}

                                    <a class="footer-top__social" href="{{ social.link }}" target="_blank" rel="nofollow">
                                        {{ svg.default(social.icon) }}
                                    </a>

                                {% endfor %}
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="wrapper">
            <p class="footer-bottom__copyright">Copyright</p>
        </div>
    </div>
</footer>

templates/app/site/general/head.html.twig
<head>

    {% set absolute_page_url = app.request.schemeAndHttpHost ~ app.request.requestUri %}
    {% set global_data = global_data.data %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="{{ page.seo.description }}">
    <meta name="keywords" content="{{ page.seo.keywords }}">
    <meta name="theme-color" content="#ffffff">

    {% if global_data.siteNameOnTitle and global_data.siteName %}
        <meta property="og:title" content="{{ page.seo.title }} — {{ global_data.siteName }}">
    {% else %}
        <meta property="og:title" content="{{ page.seo.title }}">
    {% endif %}

    <meta property="og:description" content="{{ page.seo.description }}">

    {% if page.type is defined and page.type == 'article' %}
        <meta property="og:type" content="article">
    {% else %}
        <meta property="og:type" content="website">
    {% endif %}

    <meta property="og:url" content="{{ absolute_page_url }}">
    <meta property="og:locale" content="{{ global_data.siteLang }}">

    {% if global_data.shareUserAgents|length %}

    {% else %}

        {% if page.seo.image and page.seo.image.default %}
            <meta property="og:image" content="{{ absolute_url(page.seo.image.default) }}">
        {% else %}
            <meta property="og:image" content="{{ absolute_url(global_data.defaultShareImage) }}">
        {% endif %}

    {% endif %}

    <meta name="yandex-verification" content="95da9f29a3158eaf">

    {% if page.seo.canonical %}
        <link rel="canonical" href="{{ absolute_url(page.seo.canonical) }}">
    {% else %}
        <link rel="canonical" href="{{ absolute_page_url }}">
    {% endif %}

    <link rel="icon" type="img/png" href="{{ asset('app/favicons/favicon-16x16.png') }}" sizes="16x16">
    <link rel="icon" type="img/png" href="{{ asset('app/favicons/favicon-32x32.png') }}" sizes="32x32">
    <link rel="icon" type="img/png" href="{{ asset('app/favicons/favicon-96x96.png') }}" sizes="96x96">
    <link rel="icon" type="img/png" href="{{ asset('app/favicons/favicon-120x120.png') }}" sizes="120x120">
    <link rel="icon" type="img/png" href="{{ asset('app/favicons/favicon-128x128.png') }}" sizes="128x128">
    <link rel="icon" type="img/png" href="{{ asset('app/favicons/favicon-160x160.png') }}" sizes="160x160">
    <link rel="icon" type="img/png" href="{{ asset('app/favicons/favicon-196x196.png') }}" sizes="196x196">
    <link rel="icon" type="img/png" href="{{ asset('app/favicons/favicon-228x228.png') }}" sizes="228x228">
    <link rel="apple-touch-icon" href="{{ asset('app/favicons/apple-touch-favicon-57x57.png') }}" sizes="57x57">
    <link rel="apple-touch-icon" href="{{ asset('app/favicons/apple-touch-favicon-60x60.png') }}" sizes="60x60">
    <link rel="apple-touch-icon" href="{{ asset('app/favicons/apple-touch-favicon-72x72.png') }}" sizes="72x72">
    <link rel="apple-touch-icon" href="{{ asset('app/favicons/apple-touch-favicon-76x76.png') }}" sizes="76x76">
    <link rel="apple-touch-icon" href="{{ asset('app/favicons/apple-touch-favicon-114x114.png') }}" sizes="114x114">
    <link rel="apple-touch-icon" href="{{ asset('app/favicons/apple-touch-favicon-120x120.png') }}" sizes="120x120">
    <link rel="apple-touch-icon" href="{{ asset('app/favicons/apple-touch-favicon-144x144.png') }}" sizes="144x144">
    <link rel="apple-touch-icon" href="{{ asset('app/favicons/apple-touch-favicon-152x152.png') }}" sizes="152x152">
    <link rel="apple-touch-icon" href="{{ asset('app/favicons/apple-touch-favicon-180x180.png') }}" sizes="180x180">

    {% block prepend_stylesheets %}{% endblock %}

    {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('app/build/common_css.css') }}">
    {% endblock %}

    {% block append_stylesheets %}{% endblock %}

    {% if global_data.siteNameOnTitle and global_data.siteName %}
        <title>{{ page.seo.title }} — {{ global_data.siteName }}</title>
    {% else %}
        <title>{{ page.seo.title }}</title>
    {% endif %}

    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MGVRNP7');</script>
    <!-- End Google Tag Manager -->

</head>

templates/app/site/general/header.html.twig
{% import 'app/site/macros/svg.html.twig' as svg %}

{% set page_url = app.request.requestUri %}

<header class="header">
    <div class="wrapper">

        <div class="header__wrapper box">

            {% if page_url == '/' %}
                <div class="header__logo is-main">
                    <p class="header__logo-text">Лапа Кота</p>
                    <div class="header__logo-icon">
                        {{ svg.default('cat-paw') }}
                    </div>
                </div>
            {% else %}
                <a class="header__logo" href="/">
                    <span class="header__logo-text">Лапа Кота</span>
                    <span class="header__logo-icon">
                        {{ svg.default('cat-paw') }}
                    </span>
                </a>
            {% endif %}

            <nav class="header__nav">

                {% if navigation.categories %}
                    {% for item in navigation.categories|orderFilter %}

                        {% set category = item.category %}

                        {% if category.published and category.path %}

                            {% if category.path == page.data.path %}
                                <span class="header__nav-link is-active">{{ item.name }}</span>
                            {% else %}
                                <a class="header__nav-link" href="{{ path('category', {category_path: category.path}) }}">{{ item.name }}</a>
                            {% endif %}

                        {% endif %}

                    {% endfor %}
                {% endif %}

            </nav>

            <div class="header__mobile-menu-btn js-open-mobile-menu" data-open-popup="mobile-menu">
                {{ svg.default('menu') }}
            </div>

{#            <div class="header__lk">#}

{#                {% if user %}#}
{#                    <div class="header__user-block">#}
{#                        <a class="header__user-avatar" href="{{ path('profile', {path: ''}) }}">#}

{#                            {% if user.avatar %}#}
{#                                {{ svg.color(user.avatar) }}#}
{#                            {% else %}#}
{#                                {% set avatars = ['bear', 'boar', 'chicken', 'deer', 'dog', 'fox', 'frog', 'gorilla', 'hamster', 'koala', 'lion', 'monkey', 'mouse', 'owl', 'panda', 'penguin', 'pig', 'rabbit', 'tiger', 'wolf'] %}#}
{#                                {{ svg.color(random(avatars)) }}#}
{#                            {% endif %}#}

{#                        </a>#}
{#                        <a class="header__user-logout" href="{{ global_data.fields.logout_path.value }}">Выйти</a>#}
{#                    </div>#}
{#                {% else %}#}
{#                    <div class="header__lk-item">#}
{#                        <p class="header__lk-item-title js-open-popup" data-open-popup="login">#}
{#                            Вход#}
{#                        </p>#}
{#                    </div>#}
{#                    <div class="header__lk-item">#}
{#                        <p class="header__lk-item-title js-open-popup" data-open-popup="registration">#}
{#                            Регистрация#}
{#                        </p>#}
{#                    </div>#}
{#                {% endif %}#}
{#            </div>#}

        </div>

    </div>
</header>